name: Run Unit Tests
inputs:
  python-version:
    description: "Python version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Dependencies
      shell: bash
      run: ./install.sh "dev"
    - name: Run Unit Tests
      shell: bash
      run: ./tests/system_tests/run-unit-tests.sh
