from dataclasses import dataclass

from infrastructure.config.models.config_health_report import ConfigHealthReport
from infrastructure.database.models.database_health_report import DatabaseHealthReport
from infrastructure.logging.models.logger_health_report import LoggerHealthReport
from infrastructure.models.abc_health_report import HealthReport
from infrastructure.system_monitoring.models.hardware_util_health_report import HardwareUtilHealthReport


@dataclass
class FullHealthReport(HealthReport):
  config_health_report: ConfigHealthReport
  database_health_report: DatabaseHealthReport
  hardware_util_health_report: HardwareUtilHealthReport
  logger_health_report: LoggerHealthReport
