name: Pytest
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install .
          pip install .[dev]
      - name: Run tests
        run: pytest -v
