name: POST an Account, then GET the Account
runs:
  using: "composite"
  steps:
    - name: Run Database
      shell: bash
      run: sudo PYTHONPATH=. .venv/bin/python ./scripts/deploy_db.py test
    - name: POST and GET Account
      shell: bash
      run: ./tests/system/api/post-and-get-account.sh
