name: shell-retry
inputs:
  command:
    required: true
  retries:
    required: true
  sleep:
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        for ((i=1; i<=${{ inputs.retries }}; i++)); do
          echo "▶️ Attempt $i/${{ inputs.retries }}..."
          if eval "${{ inputs.command }}"; then
            echo "✅ Success on attempt $i"
            exit 0
          fi
          echo "⚠️ Attempt $i failed; retrying in ${{ inputs.sleep }}s..."
          sleep ${{ inputs.sleep }}
        done
        echo "❌ Command failed after ${{ inputs.retries }} attempts."
        exit 1