from typing import Protocol

from domain.subdomain.entities.account import Account


class AccountRepositoryInterface(Protocol):
  def create(self, account: Account) -> Account: ...
  def get(self, ulid: str) -> Account: ...
  def update(self, account: Account) -> Account: ...
  def delete(self, ulid: str) -> Account: ...
