from typing import Protocol

from domain.subdomain.entities.membership import Membership


class MembershipRepositoryInterface(Protocol):
  def create(self, membership: Membership) -> Membership: ...
  def get(self, ulid: str) -> Membership: ...
  def get_by_user_ulid(self, user_ulid: str) -> Membership: ...
  def update(self, membership: Membership) -> Membership: ...
  def delete(self, ulid: str) -> Membership: ...
