from typing import Protocol

from domain.subdomain.entities.permission import Permission


class PermissionRepositoryInterface(Protocol):
  def create(self, permission: Permission) -> Permission: ...
  def get(self, ulid: str) -> Permission: ...
  def update(self, permission: Permission) -> Permission: ...
  def delete(self, ulid: str) -> Permission: ...
