from typing import Protocol

from domain.subdomain.entities.role import Role


class RoleRepositoryInterface(Protocol):
  def create(self, role: Role) -> Role: ...
  def get(self, ulid: str) -> Role: ...
  def update(self, role: Role) -> Role: ...
  def delete(self, ulid: str) -> Role: ...
