from typing import Protocol

from domain.entities.user import User


class UserRepositoryInterface(Protocol):
  def create(self, user: User) -> User: ...
  def get(self, uuid: str) -> User: ...
  def update(self, user: User) -> User: ...
  def delete(self, uuid: str) -> User: ...
