from typing import Protocol

from infrastructure.auth.models.user_credential import UserCredential


class UserCredentialRepositoryInterface(Protocol):
  def create(self, user: UserCredential) -> UserCredential: ...
  def get(self, ulid: str) -> UserCredential: ...
  def update(self, user: UserCredential) -> UserCredential: ...
  def delete(self, ulid: str) -> UserCredential: ...
