name: API Health Check
inputs:
  python-version:
    description: "Python version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Dependencies
      shell: bash
      run: ./install.sh "test"
    - name: Run Database
      shell: bash
      run: sudo PYTHONPATH=. .venv/bin/python ./scripts/deploy_db.py test
    - name: API Health Check
      shell: bash
      run: ./tests/system/api/health-check.sh