name: API Health Check
runs:
  using: "composite"
  steps:
    - name: Run Database
      shell: bash
      run: sudo PYTHONPATH=. .venv/bin/python ./scripts/deploy_db.py test
    - name: API Health Check
      shell: bash
      run: ./tests/system/api/health-check.sh
