from enum import Enum


class EnvVar(str, Enum):
  CPU_CHECK_INTERVAL_SECONDS = "PROJECTNAME_CPU_CHECK_INTERVAL_SECONDS"
  CPU_MAXIMUM_HEALTHY_USAGE_PERCENTAGE = "PROJECTNAME_CPU_MAXIMUM_HEALTHY_USAGE_PERCENTAGE"
  DATABASE_ENGINE = "PROJECTNAME_DATABASE_ENGINE"
  DATABASE_HOST = "PROJECTNAME_DATABASE_HOST"
  DATABASE_NAME = "PROJECTNAME_DATABASE_NAME"
  DATABASE_PASSWORD = "PROJECTNAME_DATABASE_PASSWORD"
  DATABASE_PORT = "PROJECTNAME_DATABASE_PORT"
  DATABASE_USERNAME = "PROJECTNAME_DATABASE_USERNAME"
  DEPLOYMENT_ENVIRONMENT = "PROJECTNAME_DEPLOYMENT_ENVIRONMENT"
  DISK_MAXIMUM_HEALTHY_USAGE_PERCENTAGE = "PROJECTNAME_DISK_MAXIMUM_HEALTHY_USAGE_PERCENTAGE"
  EXTERNAL_SERVICES_REQUEST_TIMEOUT = "PROJECTNAME_EXTERNAL_SERVICES_REQUEST_TIMEOUT"
  GLOBAL_CONFIG_DIR = "PROJECTNAME_GLOBAL_CONFIG_DIR"
  LOGGER_LEVEL = "PROJECTNAME_LOGGER_LEVEL"
  LOGGER_TIMEZONE = "PROJECTNAME_LOGGER_TIMEZONE"
  MEMORY_MAXIMUM_HEALTHY_USAGE_PERCENTAGE = "PROJECTNAME_MEMORY_MAXIMUM_HEALTHY_USAGE_PERCENTAGE"
  TYPICODE_PLACEHOLDER = "PROJECTNAME_TYPICODE_PLACEHOLDER"
