name: Pythonic Linting
on:
  workflow_call:
jobs:
  isort:
    uses: ./.github/workflows/lint/isort.yml
  mypy:
    uses: ./.github/workflows/lint/mypy.yml
  pylint:
    uses: ./.github/workflows/lint/pylint.yml
  ruff:
    uses: ./.github/workflows/lint/ruff.yml
