name: POSTs an entity, then GETs the entity
on:
  workflow_call:
jobs:
  CHANGE_ME-server:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - name: Set database config
        run: bash |
          ...
      - name: Start server
        run: bash "./start-with-uvicorn.sh"
  # Work in progress -- Non-functional
  CHANGE_ME-client:
    environment: test
    needs: CHANGE_ME-server
    runs-on: ubuntu-latest
    steps:
      - name: curl the server
        run: |
          curl --location 'http://127.0.0.1:8000/api/v1/job_listing' \
            --header 'Content-Type: application/json' \
            --data '{
              "title": "Some Title",
              "company": "Some Company",
              "location": "Some Location",
              "url": "https://glassdoor.com/job/some_url",
              "language": "English",
              "platform": "Glassdoor",
              "min_yoe": 2.0,
              "max_yoe": 5.0,
              "min_pay": 70000.0,
              "max_pay": 100000.0,
              "description": "Some description.",
              "post_time": "2025-10-21T14:00:00"
            }'
