from interfaces.rest.health.dto.res.base_get_health_report_res import GetHealthReportRes
from interfaces.rest.health.dto.res.get_config_parser_health_report_res import GetConfigParserHealthReportRes
from interfaces.rest.health.dto.res.get_cpu_health_report_res import GetCpuHealthReportRes
from interfaces.rest.health.dto.res.get_database_health_report_res import GetDatabaseHealthReportRes
from interfaces.rest.health.dto.res.get_disk_health_report_res import GetDiskHealthReportRes
from interfaces.rest.health.dto.res.get_environment_health_report_res import GetEnvironmentHealthReportRes
from interfaces.rest.health.dto.res.get_logger_health_report_res import GetLoggerHealthReportRes
from interfaces.rest.health.dto.res.get_memory_health_report_res import GetMemoryHealthReportRes
from interfaces.rest.health.dto.res.get_typicode_health_report_res import GetTypicodeHealthReportRes


class GetFullHealthReportRes(GetHealthReportRes):
  get_config_parser_health_report_res: GetConfigParserHealthReportRes
  get_cpu_health_report_res: GetCpuHealthReportRes
  get_database_health_report_res: GetDatabaseHealthReportRes
  get_disk_health_report_res: GetDiskHealthReportRes
  get_environment_health_report_res: GetEnvironmentHealthReportRes
  get_logger_health_report_res: GetLoggerHealthReportRes
  get_memory_health_report_res: GetMemoryHealthReportRes
  get_typicode_health_report_res: GetTypicodeHealthReportRes
