name: POST an Account, then GET the Account
runs:
  using: "composite"
  steps:
    - name: Run Database
      shell: bash
      run: sudo PYTHONPATH=. .venv/bin/python ./scripts/deploy_db.py test
    - name: GET Blog Post
      shell: bash
      run: ./tests/system/api/get-blog-post.sh
