from typing import Protocol

from shared.models.health_reports.logger_health_report import LoggerHealthReport


class LoggerInterface(Protocol):
  def get_health_report(self) -> LoggerHealthReport: ...
  def debug(self, msg: str, *args, **kwargs): ...
  def info(self, msg: str, *args, **kwargs): ...
  def warning(self, msg: str, *args, **kwargs): ...
  def error(self, msg: str, *args, **kwargs): ...
  def critical(self, msg: str, *args, **kwargs): ...
