from typing import Protocol

from infrastructure.logger.models.logger_health_report import LoggerHealthReport


class LoggerInterface(Protocol):
  def get_health_report(self) -> LoggerHealthReport: ...
  def debug(self, msg: str, *args, **kwargs) -> None: ...
  def info(self, msg: str, *args, **kwargs) -> None: ...
  def warning(self, msg: str, *args, **kwargs) -> None: ...
  def error(self, msg: str, *args, **kwargs) -> None: ...
  def critical(self, msg: str, *args, **kwargs) -> None: ...
