from typing import Protocol

class LoggerInterface(Protocol):
  def debug(self, msg: str, *args, **kwargs): ...
  def info(self, msg: str, *args, **kwargs): ...
  def warning(self, msg: str, *args, **kwargs): ...
  def error(self, msg: str, *args, **kwargs): ...
  def critical(self, msg: str, *args, **kwargs): ...
