name: POSTs an entity, then GETs the entity
inputs:
  python-version:
    description: "Python version to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Start server
      shell: bash
      run: bash "./start-with-uvicorn.sh" &
    - name: Wait for server to start
      shell: bash
      run: sleep 30   # TODO: This is a placeholder. DO NOT leave this
    - name: POST and GET the entity
      shell: bash
      run: |
        curl \
          --location 'http://127.0.0.1:8000/api/v1/job_listing' \
          --header 'Content-Type: application/json' \
          --data '{
            "title": "Some Title",
            "company": "Some Company",
            "location": "Some Location",
            "url": "https://glassdoor.com/job/some_url",
            "language": "English",
            "platform": "Glassdoor",
            "min_yoe": 2.0,
            "max_yoe": 5.0,
            "min_pay": 70000.0,
            "max_pay": 100000.0,
            "description": "Some description.",
            "post_time": "2025-10-21T14:00:00"
          }'