name: Run all unit tests
on:
  workflow_call:
jobs:
  pytest:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/unit-tests
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
